swagger: "2.0"

# TODOs:
#   - Add authentication and authorization
#   - Add meta: ToS, License, Contact info, ...



info:
  version: '0.0.1'
  title: 'Rollup Proof Generator'
  description: 'API specification for the proof generation service of the rollup.'
host: localhost:8080

paths:
  /input:
    post:
      operationId: postInput
      tags:
      - Proof Generator
      summary: Send inputs to generate a proof
      description: Send a petition of proo generation based on inputs. Note that this endpoint will just schedule the proof generation, not return it.
      parameters:
      - in: body
        required: true
        name: Input
        description: Input for the proof generation circuit.
        schema:
          $ref: '#/definitions/input'
      produces:
      - application/json
      responses:
        200:
          description: successful operation
        401:
          description: Input validation error
          schema:
            $ref: '#/definitions/Unauthorized'
        500:
          description: Internal server
          schema:
            $ref: '#/definitions/Error'
        501:
          description: Not implemented
          schema:
            $ref: '#/definitions/NotImplemented'
  /status:
    get:
      operationId: getStatus
      tags:
      - Proof Generator
      summary: Get the status of the proof generator.
      description: Returns the status of the proof generator.
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/status'
        401:
          description: Input validation error
          schema:
            $ref: '#/definitions/Unauthorized'
        500:
          description: Internal server
          schema:
            $ref: '#/definitions/Error'
        501:
          description: Not implemented
          schema:
            $ref: '#/definitions/NotImplemented'
  /cancel:
    post:
      operationId: postCancel
      tags:
      - Proof Generator
      summary: Abort the proof that is currentl being generated
      description: Send a petition to abort the creation process of a proof
      responses:
        200:
          description: successful operation
        401:
          description: Input validation error
          schema:
            $ref: '#/definitions/Unauthorized'
        500:
          description: Internal server
          schema:
            $ref: '#/definitions/Error'
        501:
          description: Not implemented
          schema:
            $ref: '#/definitions/NotImplemented'
          
definitions:
  # TODO: add feePlanCoins and feePlanFees descriptions
  input:
    type: object
    description: Set of input signals required to generate a proof
    properties:
      oldStateRoot:
        type: string
        description: Root of the old state tree hashed, encoded as a string representing a 256 bits unsigned integer
        pattern: ^\d{1,78}$
        example: "12345678123456781234567812345678"
      feePlanCoins:
        type: string
        description: ??????, encoded as a string representing a 256 bits unsigned integer
        pattern: ^\d{1,78}$
        example: "869703547053246980532469870325487605342"
      feePlanFees:
        type: string
        description: ???????, encoded as a string representing a 256 bits unsigned integer
        pattern: ^\d{1,78}$
        example: "87634526780543268793542986754328763459807"
    required:
    - oldStateRoot
    - feePlanCoins
    - feePlanFees
  # TODO: check proof format add regex validation and redo example according to it
  status:
    type: object
    properties:
      status:
        type: string
        enum:
        - Idle
        - Error
        - Pending
        - Finished 
        description: >
          Possible states of the proof service:
           * `Idle` - waiting for input
           * `Error` - if witness is not correct
           * `Pending` - if proof is being generated
           * `Finished` - if proof has been generated, in that case proof will be returned
      proof:
        type: string
        description: successfully generated proof. When this field is included in the response the value of status will always be `Finished`
        # pattern: ^\d{1,78}$
        # example: ...
    example:
      status: Finished
      proof: add propper example here as well
    required:
    - status
    
  Error:
    description: Internal server error
    type: object
    properties:
      code:
        type: string
        example: UNKNOWN_ERROR
      message:
        type: string
        example: This is emabarrasing, something went wrong while processing your request. Try again later, if the rror persist please contact support.
    required:
    - code
    - message
  Unauthorized:
    description: Unauthorized
    type: object
    properties:
      code:
        type: string
        example: INPUT_VALIDATION_ERROR
      message:
        type: string
        example: Incorrect value for \"id\" at paths,/transaction/{id},get,parameters,0,schema.
    required:
    - code
    - message
  NotImplemented:
    description: Not Implemented
    type: object
    properties:
      code:
        type: string
        example: FEATURE_NOT_IMPLEMENTED_YET
      message:
        type: string
        example: This feature is not fully implemented yet. You can use the mockup data provided in this response but keep in mind that the values are reandomly generated.
      mockup:
        type: object
        example: 
          thisObject: 'Sould be equal to the 200 response object'
                     
    required:
    - code
    - message
