---
swagger: "2.0"
info:
  description: "API specification for the proof generation service of the rollup."
  version: "0.0.1"
  title: "Rollup Proof Generator"
host: "localhost:8080"
paths:
  /input:
    post:
      tags:
      - "Proof Generator"
      summary: "Send inputs to generate a proof"
      description: "Send a petition of proo generation based on inputs. Note that\
        \ this endpoint will just schedule the proof generation, not return it."
      operationId: "postInput"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Input"
        description: "Input for the proof generation circuit."
        required: true
        schema:
          $ref: "#/definitions/input"
      responses:
        200:
          description: "successful operation"
        401:
          description: "Input validation error"
          schema:
            $ref: "#/definitions/Unauthorized"
        500:
          description: "Internal server"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Not implemented"
          schema:
            $ref: "#/definitions/NotImplemented"
      x-swagger-router-controller: "ProofGenerator"
  /status:
    get:
      tags:
      - "Proof Generator"
      summary: "Get the status of the proof generator."
      description: "Returns the status of the proof generator."
      operationId: "getStatus"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/status"
        401:
          description: "Input validation error"
          schema:
            $ref: "#/definitions/Unauthorized"
        500:
          description: "Internal server"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Not implemented"
          schema:
            $ref: "#/definitions/NotImplemented"
      x-swagger-router-controller: "ProofGenerator"
  /cancel:
    post:
      tags:
      - "Proof Generator"
      summary: "Abort the proof that is currentl being generated"
      description: "Send a petition to abort the creation process of a proof"
      operationId: "postCancel"
      parameters: []
      responses:
        200:
          description: "successful operation"
        401:
          description: "Input validation error"
          schema:
            $ref: "#/definitions/Unauthorized"
        500:
          description: "Internal server"
          schema:
            $ref: "#/definitions/Error"
        501:
          description: "Not implemented"
          schema:
            $ref: "#/definitions/NotImplemented"
      x-swagger-router-controller: "ProofGenerator"
definitions:
  input:
    type: "object"
    required:
    - "feePlanCoins"
    - "feePlanFees"
    - "oldStateRoot"
    properties:
      oldStateRoot:
        type: "string"
        example: "12345678123456781234567812345678"
        description: "Root of the old state tree hashed, encoded as a string representing\
          \ a 256 bits unsigned integer"
        pattern: "^\\d{1,78}$"
      feePlanCoins:
        type: "string"
        example: "869703547053246980532469870325487605342"
        description: "??????, encoded as a string representing a 256 bits unsigned\
          \ integer"
        pattern: "^\\d{1,78}$"
      feePlanFees:
        type: "string"
        example: "87634526780543268793542986754328763459807"
        description: "???????, encoded as a string representing a 256 bits unsigned\
          \ integer"
        pattern: "^\\d{1,78}$"
    description: "Set of input signals required to generate a proof"
  status:
    type: "object"
    required:
    - "status"
    properties:
      status:
        type: "string"
        description: "Possible states of the proof service:\n * `Idle` - waiting for\
          \ input\n * `Error` - if witness is not correct\n * `Pending` - if proof\
          \ is being generated\n * `Finished` - if proof has been generated, in that\
          \ case proof will be returned\n"
        enum:
        - "Idle"
        - "Error"
        - "Pending"
        - "Finished"
      proof:
        type: "string"
        description: "successfully generated proof. When this field is included in\
          \ the response the value of status will always be `Finished`"
    example:
      status: "Finished"
      proof: "add propper example here as well"
  Error:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "string"
        example: "UNKNOWN_ERROR"
      message:
        type: "string"
        example: "This is emabarrasing, something went wrong while processing your\
          \ request. Try again later, if the rror persist please contact support."
    description: "Internal server error"
  Unauthorized:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "string"
        example: "INPUT_VALIDATION_ERROR"
      message:
        type: "string"
        example: "Incorrect value for \\\"id\\\" at paths,/transaction/{id},get,parameters,0,schema."
    description: "Unauthorized"
  NotImplemented:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "string"
        example: "FEATURE_NOT_IMPLEMENTED_YET"
      message:
        type: "string"
        example: "This feature is not fully implemented yet. You can use the mockup\
          \ data provided in this response but keep in mind that the values are reandomly\
          \ generated."
      mockup:
        type: "object"
        example:
          thisObject: "Sould be equal to the 200 response object"
        properties: {}
    description: "Not Implemented"
